version: '3.9'
services:


  app:
    container_name: app
    restart: always
    build: .
    ports:
      - 8080:8080
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules


  postgres:
    container_name: db
    image: postgres:16
    ports:
      - '5433:${DB_PORT}'
    volumes:
      - data:/data/db
      # - ./src/infrastructure/db/migrations:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}


volumes:
  data: {}