version: '3.9'
services:


  app:
    container_name: app
    restart: always
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules


  db:
    container_name: db
    image: postgres:16
    # command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0
    ports:
      - '5433:${DB_PORT}'
    volumes:
      - data:/data/db
      # - ./src/infrastructure/db/migrations:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}


volumes:
  data: {}